# Generated by Django 4.2.6 on 2023-10-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='value_rest_to_pay',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='value_total_price',
            field=models.FloatField(),
        ),
    ]
