# Generated by Django 4.2.6 on 2023-10-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='information',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
