# Generated by Django 4.2.6 on 2023-12-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contract', '0002_alter_contract_value_rest_to_pay_and_more'),
        ('Event', '0002_alter_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Contract.contract'),
        ),
    ]
